name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.13t']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install -r requirements-dev.txt
      - name: Lint
        run: make lint
